### ISSUE TITLE
Create new wrenchKey method.

### ISSUE THREAD

**Issue by gchenfc** [borglab/GTDynamics#10]
This issue was imported from [github.gatech.edu](https://github.gatech.edu/borglab/GTDynamics/issues/36).
The original issue was opened by @smccormick32 on 2020-05-21T19:52:53Z
---
(From PR https://github.gatech.edu/borglab/GTDynamics/pull/27 )

comment from ScrewJointBase.h, line 349:

create a new wrenchKey(link, t) method in this class (or its base class) and use it everywhere.
same for TorqueKey ->torqueKey, JointAngleKey -> angleKey, JointVelKey -> velocityKey, JointAccelKey -> accelerationKey

**Comment by varunagrawal** [comment]
This issue doesn't seem valid because `WrenchKey` expects the link ID, joint ID and time index. So it would be `wrenchKey(link, joint, t)`, which seems a bit pointless.

@dellaert ?

**Comment by gchenfc** [comment]
I think this was resolved by #65
