### ISSUE TITLE
convert all shared pointers in tests to stack-allocated instances

### ISSUE THREAD

**Issue by gchenfc** [borglab/GTDynamics#14]
This issue was imported from [github.gatech.edu](https://github.gatech.edu/borglab/GTDynamics/issues/48).
The original issue was opened by @smccormick32 on 2020-07-08T15:25:16Z
---
From review of PR https://github.gatech.edu/borglab/GTDynamics/pull/47, line 65 in `testPrismaticJoint.cpp` and line 55 in `testScrewJoint.cpp`. (This is likely also present in `testRevoluteJoint.cpp`, and may show up in other tests as well.)

Here is an example of what that looks like currently, where `j1` is the shared pointer to be converted in this case:
```
EXPECT(j1->getJointParameters().effort_type == Joint::JointEffortType::Actuated);
```

**Comment by varunagrawal** [comment]
List of files this needs to be updated in:
1. `testSdf.cpp`
2. `testHelicalJoint.cpp`
3. `testPrismaticJoint.cpp`
