### ISSUE TITLE
Refactor link/joint frames

### ISSUE THREAD

**Issue by dellaert** [borglab/GTDynamics#203]
Get rid of *all* frames except COM frames in links, and in a joint have a `parentTj` and `jTchild` pose. I think that way we can make revolute joints *very* efficient, as many zeros will appear in `parentTchild = parentTj * exp(q) * jTchild`.

The dreaded `wTl` frames can be computed via FK with zero values.

**Comment by varunagrawal** [comment]
@dellaert I believe this has been accomplished via #238, #259 and #267?

**Comment by dellaert** [comment]
Yup
