### ISSUE TITLE
Changing map to vector in Robot.h in storing links and joints

### ISSUE THREAD

**Issue by yetongumich** [borglab/GTDynamics#220]
Use vector to store links and joints.

Do a linear search in requesting a joint/link by name.

**Comment by varunagrawal** [comment]
@yetongumich?

**Comment by varunagrawal** [comment]
Ping @yetongumich

**Comment by varunagrawal** [comment]
Closing due to no response. As detailed in my above comment, a map's constant time access is preferred instead of searching through a vector.
