### ISSUE TITLE
Remove JointCoordinateType

### ISSUE THREAD

**Issue by varunagrawal** [borglab/GTDynamics#271]
`JointTyped` defines two aliases, `JointCoordinateType` and `JointCoordinate` which is the same as `JointCoordinate`. The majority of the code uses `JointCoordinate` while only `JointLimitFactors.h` uses `JointCoordinateType`.

This kind of aliasing is confusing, and unless someone can convince me with a _compelling_ argument otherwise, we should get rid of `JointCoordinateType`.

**Comment by varunagrawal** [comment]
@gchenfc @yetongumich can you please let me know if I am missing something and why JointCoordinateType should not be deleted? We should also take some time to add in the ball and sphere joints soon since that may illuminate the usefulness of `JointTyped` going forward.

**Comment by gchenfc** [comment]
Resolved by #291 that removed all these things.
