### ISSUE TITLE
LinkSharedPtrs in RobotTypes.h

### ISSUE THREAD

**Issue by gchenfc** [borglab/GTDynamics#8]
This issue was imported from [github.gatech.edu](https://github.gatech.edu/borglab/GTDynamics/issues/32).
The original issue was opened by @smccormick32 on 2020-05-12T16:17:16Z
---
Suggestions from PR #27:

- Avoid kitchen-sink header (including many headers even if they're unused); instead, have a header defining the macro and call that macro in each header.
- Eliminate this pattern? (not much difference between std::shared_ptr and LinkSharedPtr, will be using auto anyway)

**Comment by dellaert** [comment]
Not sure what this issue is about, @gchenfc . Close if no longer important?

**Comment by gchenfc** [comment]
I can't remember what this was about - I guess this was from the old github.gatech repo that I didn't open, but that I just imported here under my name.

Closing since I'm sure it would have come up earlier if it were important.
